POST : http://localhost:3000/books
{
  "title": "Test",
  "author": "Eman Arroub",
  "totalCopies": 1,
}

POST : http://localhost:3000/members
{
    "name" : "eman",
    "email" : "eman@test.com",
}

POST : http://localhost:3000/borrow
{
    "memberId" : 1,
    "bookId":1
}

PATCH : http://localhost:3000/borrow/1/return

PUT : http://localhost:3000/books|members/1

DELETE : http://localhost:3000/books|members/1

PATCH : http://localhost:3000/members/2/role
{
    "role": "librarian"
}






